# Generated by Django 3.1.7 on 2021-03-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='baekjoon_id',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
