# Generated by Django 3.1.7 on 2021-04-10 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solvedUsers',
            field=models.ManyToManyField(related_name='solvedProblems', through='problems.SolvedProblems', to=settings.AUTH_USER_MODEL),
        ),
    ]
